version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "3002:3002"
    container_name: server-side

  client:
    build:
      context: ./client
    ports:
      - "5001:5001"
    container_name: client-side
    stdin_open: true
